// We import the icons from lucide-react and immediately export them with an "Icon" suffix
// for consistent naming across the application.
export { 
    Crosshair as LogoIcon,
    Dumbbell as DumbbellIcon, 
    Home as HomeIcon, 
    Clock as ClockIcon, 
    ArrowRight as ArrowRightIcon, 
    ArrowLeft as ArrowLeftIcon,
    Building as BuildingIcon, 
    Award as AwardIcon,
    Weight as WeightIcon,
    Flame as FlameIcon,
    Timer as TimerIcon,
    Target as TargetIcon,
    RefreshCw as RefreshCwIcon,
    Info as InfoIcon,
    Sun as SunIcon,
    Moon as MoonIcon,
    Replace as ReplaceIcon,
    CheckSquare as CheckSquareIcon,
    CheckCircle2 as CheckCircle2Icon,
    Play as PlayIcon,
    Pause as PauseIcon,
    Undo2 as Undo2Icon,
    History as HistoryIcon,
    User as UserIcon,
    Trophy as TrophyIcon,
    Medal as MedalIcon,
    LineChart as LineChartIcon,
    Zap as ZapIcon,
    X as XIcon,
    Video as VideoIcon,
    Calendar as CalendarIcon,
    GitCompareArrows as GitCompareArrowsIcon,
    // New Icons for Gamification
    BrainCircuit as BrainCircuitIcon,
    Repeat as RepeatIcon,
    Mountain as MountainIcon,
    Sparkles as SparklesIcon,
    Diamond as DiamondIcon,
    Lock as LockIcon,
    Star as StarIcon,
    ArrowUp as ArrowUpIcon,
    // New Icons for Planner
    ClipboardList as ClipboardListIcon,
    PlusCircle as PlusCircleIcon,
    Trash2 as Trash2Icon,
    Edit as EditIcon,
    ChevronLeft as ChevronLeftIcon,
    ChevronRight as ChevronRightIcon,
    // New Icons for Profile Edit
    Camera as CameraIcon,
    Instagram as InstagramIcon,
    ImagePlus as ImagePlusIcon,
} from 'lucide-react';